### ISSUE TITLE
Operator balancing 

### ISSUE THREAD

**Issue by hm-lnkd** [Nicholas-Baron/kt-calc#7]
Input: 
`1+2+3+4+`

Expected:
`unbalanced operator`

Result:
`Invalid expression
Exception in thread "main" java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:362)
	at java.base/java.util.ArrayDeque.pop(ArrayDeque.java:593)
	at EvaluationKt.eval(Evaluation.kt:19)
	at MainKt.main(main.kt:18)
	at MainKt.main(main.kt)`

**Comment by Nicholas-Baron** [comment]
Branch with a potential fix is `op-balancing`.
